// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9rw04bkxX9FmFd1NaUwNxFcL95kcX1So',
    appId: '1:654083888078:web:cd90902587ede3af68d19f',
    messagingSenderId: '654083888078',
    projectId: 'fluttermedicalapp-ab48a',
    authDomain: 'fluttermedicalapp-ab48a.firebaseapp.com',
    storageBucket: 'fluttermedicalapp-ab48a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq7dNLPaYGprV-IweaGoCIgDdb-lJTWBk',
    appId: '1:654083888078:android:a592dff6b96332df68d19f',
    messagingSenderId: '654083888078',
    projectId: 'fluttermedicalapp-ab48a',
    storageBucket: 'fluttermedicalapp-ab48a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1BeMydFg_cgnpOEexH2dtQjNExu3D7XQ',
    appId: '1:654083888078:ios:314efc463dc4dfe168d19f',
    messagingSenderId: '654083888078',
    projectId: 'fluttermedicalapp-ab48a',
    storageBucket: 'fluttermedicalapp-ab48a.appspot.com',
    iosClientId:
        '654083888078-cfe3t34qtcjokk3fd64kmtl83ucnpaln.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1BeMydFg_cgnpOEexH2dtQjNExu3D7XQ',
    appId: '1:654083888078:ios:314efc463dc4dfe168d19f',
    messagingSenderId: '654083888078',
    projectId: 'fluttermedicalapp-ab48a',
    storageBucket: 'fluttermedicalapp-ab48a.appspot.com',
    iosClientId:
        '654083888078-cfe3t34qtcjokk3fd64kmtl83ucnpaln.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalApplication',
  );
}
